version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Abhishek"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-tvnhlu1vgkw5"
s3_prefix = "Abhishek"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
disable_rollback = true
profile = "default"
parameter_overrides = "APIKEYNAME=\"AbhishekSAMGateway\" IAMRole=\"arn:aws:iam::163483727376:role/AbhishekSIAMRole\""
