version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "AbhishekS1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-szwczjsh2uck"
s3_prefix = "AbhishekS1"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
disable_rollback = true
